// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:lexi_cards/features/cards/data/models/deck_model.dart';
import 'package:lexi_cards/features/cards/data/models/flashcard_model.dart';
import 'package:lexi_cards/features/cards/data/models/review_log_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DeckModelAdapter());
    registerAdapter(FlashcardModelAdapter());
    registerAdapter(ReviewLogModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DeckModelAdapter());
    registerAdapter(FlashcardModelAdapter());
    registerAdapter(ReviewLogModelAdapter());
  }
}
